server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
              - "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RemoveResponseHeader=Access-Control-Allow-Origin
            - RemoveResponseHeader=Access-Control-Allow-Methods
            - RemoveResponseHeader=Access-Control-Allow-Headers
            - RemoveResponseHeader=Access-Control-Allow-Credentials
        - id: stock-service
          uri: lb://stock-service
          predicates:
            - Path=/api/companies/**,/api/shares/**
          filters:
            - RemoveResponseHeader=Access-Control-Allow-Origin
            - RemoveResponseHeader=Access-Control-Allow-Methods
            - RemoveResponseHeader=Access-Control-Allow-Headers
            - RemoveResponseHeader=Access-Control-Allow-Credentials

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
